train_augment:
  ToPILImage:
  RandomHorizontalFlip:
    p: 0.5
  Resize:
    size: [224, 224]
  ToTensor:

val_augment:
  ToPILImage:
  Resize:
    size: [224, 224]
  ToTensor:

dataset:
  batchsize: 32
  dataset_name: CIFAR10

model:
  name: SqueezeNet11

loss:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005

lr_schedule:
  name: StepLR
  params:
    step_size: 100
    gamma: 0.1

evaluate:
  Accuracy:

model_checkpoint:
  save_interval: 5
  n_saved: 1


epochs: 10